### ISSUE TITLE
请问大佬的具体怎么做

### ISSUE THREAD

**Issue by EternityMCUP** [KawaiiSparkle/android_iflytek_T20Pro#1]
我在另一个页面看到了你发全量包，我有些不太明白

![image](https://github.com/user-attachments/assets/3b4e8fae-537a-430c-b95d-55edd1d96f00)

**Comment by KawaiiSparkle** [comment]
全量包利用sdat2img转成各个分区的镜像。

**Comment by KawaiiSparkle** [comment]
然后利用[这个工具，当然自己编译，只有Linux版本](https://github.com/erfanoabdi/imgpatchtools)，自行利用差分包和全量包得到的分区镜像进行合成（注：一定要解压br文件，不然无法合成镜像，此外请保持sdat2img.py和win_full2img.py在同一目录下），差分包合成我用了gpt写了一套工具用来进行半自动化合成。

**Comment by KawaiiSparkle** [comment]
[otapackages_researching_tools.tar.gz](https://github.com/user-attachments/files/17355539/otapackages_researching_tools.tar.gz)

**Comment by EternityMCUP** [comment]
谢谢大佬😊
